<script setup lang="ts">
import hljs from 'highlight.js'

const props = withDefaults(defineProps<{
  code: string
  language?: string
  filename?: string
  fileSize?: number
  showToolbar?: boolean
}>(), {
  language: 'plaintext',
  filename: '',
  fileSize: 0,
  showToolbar: true
})

const { formatBytes } = useFormatters()

const isWrap = ref(false)
const isCopied = ref(false)
const searchQuery = ref('')
const isSearchOpen = ref(false)

// Map file extensions/common names to highlight.js language names
const normalizedLanguage = computed(() => {
  const lang = (props.language || '').toLowerCase().replace(/^\./, '')
  const map: Record<string, string> = {
    js: 'javascript',
    mjs: 'javascript',
    cjs: 'javascript',
    jsx: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    py: 'python',
    sh: 'bash',
    zsh: 'bash',
    yml: 'yaml',
    md: 'markdown',
    golang: 'go',
    htm: 'html',
    env: 'ini',
    conf: 'ini'
  }
  return map[lang] || lang || 'plaintext'
})

// Highlighted HTML string generated by highlight.js
const highlightedHtml = computed(() => {
  if (!props.code) return ''
  const lang = normalizedLanguage.value
  try {
    if (lang && hljs.getLanguage(lang)) {
      return hljs.highlight(props.code, { language: lang, ignoreIllegals: true }).value
    }
    return hljs.highlightAuto(props.code.slice(0, 10000)).value
  } catch {
    // Fallback: escape HTML
    return escapeHtml(props.code)
  }
})

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

// Split into lines for synchronized line numbers
const highlightedLines = computed(() => {
  return highlightedHtml.value.split('\n')
})

const rawLines = computed(() => {
  return props.code.split('\n')
})

const searchMatches = computed(() => {
  if (!searchQuery.value.trim()) return []
  const q = searchQuery.value.toLowerCase()
  return rawLines.value
    .map((line, idx) => (line.toLowerCase().includes(q) ? idx : -1))
    .filter(idx => idx !== -1)
})

function copyCode() {
  navigator.clipboard?.writeText(props.code)
  isCopied.value = true
  setTimeout(() => {
    isCopied.value = false
  }, 2000)
}
</script>

<template>
  <div class="flex flex-col h-full min-h-0 rounded-2xl border border-slate-200 dark:border-white/[0.08] bg-slate-50 dark:bg-[#090d15] overflow-hidden">
    <!-- Toolbar -->
    <div
      v-if="showToolbar"
      class="flex shrink-0 items-center justify-between gap-3 px-4 py-2 border-b border-slate-200/80 dark:border-white/[0.06] bg-white/80 dark:bg-[#121723]/90 text-xs backdrop-blur-sm"
    >
      <!-- Left: Language Badge & Meta -->
      <div class="flex items-center gap-2.5 min-w-0">
        <span class="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-lg bg-primary-500/10 text-primary-600 dark:text-primary-400 border border-primary-500/20 font-mono text-[10px] font-bold uppercase tracking-wider">
          {{ normalizedLanguage }}
        </span>
        <span v-if="filename" class="font-mono text-slate-800 dark:text-zinc-200 truncate font-medium text-[11px]">
          {{ filename }}
        </span>
        <span class="text-slate-400 dark:text-zinc-600 hidden sm:inline">•</span>
        <span class="font-mono text-slate-500 dark:text-zinc-400 text-[11px] hidden sm:inline">
          {{ rawLines.length }} lines
        </span>
        <span v-if="fileSize > 0" class="font-mono text-slate-500 dark:text-zinc-400 text-[11px] hidden md:inline">
          ({{ formatBytes(fileSize) }})
        </span>
      </div>

      <!-- Right: Controls -->
      <div class="flex items-center gap-1.5 shrink-0">
        <!-- Search Toggle -->
        <div v-if="isSearchOpen" class="flex items-center gap-1 bg-slate-100 dark:bg-[#1c2231] px-2 py-1 rounded-xl border border-slate-300 dark:border-white/10 text-xs">
          <UIcon name="i-lucide-search" class="size-3 text-slate-500 dark:text-zinc-400" />
          <input
            v-model="searchQuery"
            type="text"
            placeholder="Find in code..."
            class="bg-transparent border-none outline-none text-[11px] text-slate-800 dark:text-white w-28 font-mono"
            autofocus
          >
          <span v-if="searchQuery" class="text-[10px] text-slate-500 dark:text-zinc-400 font-mono px-1">
            {{ searchMatches.length }}
          </span>
          <button
            type="button"
            class="text-slate-400 hover:text-slate-700 dark:hover:text-white cursor-pointer"
            @click="isSearchOpen = false; searchQuery = ''"
          >
            <UIcon name="i-lucide-x" class="size-3" />
          </button>
        </div>

        <button
          v-else
          type="button"
          title="Find in code"
          class="flex size-7 items-center justify-center rounded-lg text-slate-500 hover:text-slate-900 hover:bg-slate-200/60 dark:text-zinc-400 dark:hover:text-white dark:hover:bg-white/[0.08] transition-colors cursor-pointer"
          @click="isSearchOpen = true"
        >
          <UIcon name="i-lucide-search" class="size-3.5" />
        </button>

        <!-- Word Wrap Toggle -->
        <button
          type="button"
          :title="isWrap ? 'Disable word wrap' : 'Enable word wrap'"
          class="flex items-center gap-1 px-2 py-1 rounded-lg text-[11px] font-mono transition-colors cursor-pointer"
          :class="[
            isWrap
              ? 'bg-primary-500/15 text-primary-600 dark:text-primary-400 border border-primary-500/25 font-semibold'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60 dark:text-zinc-400 dark:hover:text-white dark:hover:bg-white/[0.08]'
          ]"
          @click="isWrap = !isWrap"
        >
          <UIcon name="i-lucide-wrap-text" class="size-3.5" />
          <span class="hidden sm:inline">Wrap</span>
        </button>

        <!-- Copy Snippet Button -->
        <button
          type="button"
          class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold transition-all cursor-pointer shadow-2xs"
          :class="[
            isCopied
              ? 'bg-emerald-500 text-white'
              : 'bg-slate-200/80 hover:bg-slate-300/80 text-slate-700 hover:text-slate-900 dark:bg-[#202738] dark:hover:bg-[#283248] dark:text-zinc-200 dark:hover:text-white border border-slate-300/80 dark:border-white/10'
          ]"
          @click="copyCode"
        >
          <UIcon :name="isCopied ? 'i-lucide-check' : 'i-lucide-copy'" class="size-3.5" />
          <span>{{ isCopied ? 'Copied' : 'Copy' }}</span>
        </button>
      </div>
    </div>

    <!-- Code Editor Surface -->
    <div class="flex-1 min-h-0 overflow-auto font-mono text-xs p-3.5 leading-relaxed selection:bg-primary-500/25 select-text">
      <table class="w-full border-collapse">
        <tbody>
          <tr
            v-for="(lineHtml, idx) in highlightedLines"
            :key="idx"
            class="group transition-colors rounded"
            :class="[
              searchMatches.includes(idx)
                ? 'bg-amber-500/15 ring-1 ring-amber-500/30'
                : 'hover:bg-slate-200/50 dark:hover:bg-white/[0.03]'
            ]"
          >
            <!-- Line Number -->
            <td class="w-12 select-none text-right pr-4 text-slate-400 dark:text-zinc-600 text-[11px] align-top font-mono shrink-0">
              {{ idx + 1 }}
            </td>

            <!-- Line Content -->
            <td
              class="font-mono text-slate-900 dark:text-zinc-200 align-top hljs-line"
              :class="isWrap ? 'whitespace-pre-wrap break-all' : 'whitespace-pre'"
              v-html="lineHtml || '&nbsp;'"
            />
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style>
/* Syntax Highlighting Tokens (Light & Dark) */
.hljs-keyword,
.hljs-selector-tag,
.hljs-built_in,
.hljs-section,
.hljs-meta {
  color: #7c3aed;
  font-weight: 600;
}
.dark .hljs-keyword,
.dark .hljs-selector-tag,
.dark .hljs-built_in,
.dark .hljs-section,
.dark .hljs-meta {
  color: #a78bfa;
}

.hljs-string,
.hljs-symbol,
.hljs-bullet,
.hljs-addition {
  color: #059669;
}
.dark .hljs-string,
.dark .hljs-symbol,
.dark .hljs-bullet,
.dark .hljs-addition {
  color: #34d399;
}

.hljs-number,
.hljs-literal,
.hljs-quote {
  color: #d97706;
}
.dark .hljs-number,
.dark .hljs-literal,
.dark .hljs-quote {
  color: #fbbf24;
}

.hljs-comment,
.hljs-deletion {
  color: #64748b;
  font-style: italic;
}
.dark .hljs-comment,
.dark .hljs-deletion {
  color: #64748b;
}

.hljs-title,
.hljs-title.class_,
.hljs-title.function_ {
  color: #2563eb;
  font-weight: 600;
}
.dark .hljs-title,
.dark .hljs-title.class_,
.dark .hljs-title.function_ {
  color: #60a5fa;
}

.hljs-variable,
.hljs-template-variable,
.hljs-attr {
  color: #0284c7;
}
.dark .hljs-variable,
.dark .hljs-template-variable,
.dark .hljs-attr {
  color: #38bdf8;
}

.hljs-tag,
.hljs-name {
  color: #e11d48;
}
.dark .hljs-tag,
.dark .hljs-name {
  color: #fb7185;
}
</style>
